config/routes.rb
MedBase::Application.routes.draw do

  resources :desease_types

  resources :doctor_deseases

  resources :doctor_types

  resources :users

  resources :med_diagnostic_test_types

  resources :htm_help_types

  resources :hospitalization_types

  resources :diagnostic_test_types

  resources :ins_companies

  resources :client_sexes

  resources :clients do
    member do
      get :operations,:search
    end

   resources :lab_tests 
   resources :diagnostic_tests
   resources :hospitalizations
   resources :htm_help_notes
   resources :sanatorium_notes
   resources :med_diagnostic_tests
   resources :prof_inspections
  end

  resources :lab_test_types

  match 'csv' =>"clients#import_csv"

  root :to => 'welcome#index'  

end

app/models/diagnostic_test.rb
class DiagnosticTest < ActiveRecord::Base
  belongs_to :diagnostic_test_type
  validates :test_date,:diagnostic_test_type_id,:result, :presence => true
  belongs_to :client
end

app/models/diagnostic_test_type.rb
class DiagnosticTestType < ActiveRecord::Base
  validates :name,:presence => true
  has_many :diagnostic_tests 



def can_be_deleted
  diagnostic_tests.count<=0
end

end

app/controllers/diagnostic_tests_controller.rb
class DiagnosticTestsController < ApplicationController
  # GET /diagnostic_tests
  # GET /diagnostic_tests.json
  before_filter :find_client

  def find_client
    @client=Client.find(params[:client_id])
  end

  def index
    @diagnostic_tests = @client.diagnostic_tests

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnostic_tests }
    end
  end

  # GET /diagnostic_tests/1
  # GET /diagnostic_tests/1.json
  def show
    @diagnostic_test = DiagnosticTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnostic_test }
    end
  end

  # GET /diagnostic_tests/new
  # GET /diagnostic_tests/new.json
  def new
    @diagnostic_test = DiagnosticTest.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnostic_test }
    end
  end

  # GET /diagnostic_tests/1/edit
  def edit
    @diagnostic_test = DiagnosticTest.find(params[:id])
  end

  # POST /diagnostic_tests
  # POST /diagnostic_tests.json
  def create
    @diagnostic_test = DiagnosticTest.new(params[:diagnostic_test])
    @diagnostic_test.client=@client

    respond_to do |format|
      if @diagnostic_test.save
        format.html { redirect_to client_diagnostic_tests_path(@client), notice: I18n.t(:record_saved) }
        format.json { render json: @diagnostic_test, status: :created, location: @diagnostic_test }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnostic_tests/1
  # PUT /diagnostic_tests/1.json
  def update
    @diagnostic_test = DiagnosticTest.find(params[:id])

    respond_to do |format|
      if @diagnostic_test.update_attributes(params[:diagnostic_test])
        format.html { redirect_to client_diagnostic_tests_path(@client), notice: I18n.t(:record_updated)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_tests/1
  # DELETE /diagnostic_tests/1.json
  def destroy
    @diagnostic_test = DiagnosticTest.find(params[:id])
    @diagnostic_test.destroy

    respond_to do |format|
      format.html { redirect_to client_diagnostic_tests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/diagnostic_tests_helper.rb
module DiagnosticTestsHelper
end

app/views/diagnostic_tests/_diagnostic_test.html.haml
%p
  ="#{l item.test_date} | #{item.diagnostic_test_type.name}: #{item.result}"

app/views/diagnostic_tests/_form.html.haml
=simple_form_for [@client,@diagnostic_test] do |f|
  =f.error_notification
  =f.input :test_date,:label=>"Дата"
  =f.association :diagnostic_test_type,:label =>"Тип"
  =f.input :result,:label=>"Результат"
  =f.submit "Сохранить"

app/views/diagnostic_tests/edit.html.haml
%h1 Редактирование диагностического исследования

= render 'form'

= link_to 'Назад', client_diagnostic_tests_path(@client)

app/views/diagnostic_tests/index.html.haml
= link_to image_tag("",:class=>"ui-icon ui-icon-triangle-1-w"), operations_client_path(@client)
%br
%h1= @client.fio unless @client.nil?
%br
%h2 Диагностические исследования
%br

-unless flash.empty?
  %p#notice= notice

-if @diagnostic_tests.count > 0
  %table#newspaper-a
    %tr
      %th Дата
      %th Тип исследования
      %th Результат
      %th
      %th

    - @diagnostic_tests.each do |diagnostic_test|
      %tr
        %td= l diagnostic_test.test_date
        %td= diagnostic_test.diagnostic_test_type.name
        %td= diagnostic_test.result
        %td= link_to image_tag("",:class => "ui-icon ui-icon-pencil"),edit_client_diagnostic_test_path(@client,diagnostic_test)
        %td= link_to image_tag("",:class => "ui-icon ui-icon-minus"), client_diagnostic_test_path(@client,diagnostic_test), :confirm => 'Are you sure?', :method => :delete

-else
  =render "clients/empty"

%br

= link_to 'Новое исследование', new_client_diagnostic_test_path(@client)

app/views/diagnostic_tests/new.html.haml
%h1 Новое диагностическое исследование

= render 'form'

= link_to 'Назад', client_diagnostic_tests_path(@client)

app/views/diagnostic_tests/show.html.haml
%p#notice= notice

%p
  %b Test date:
  = @diagnostic_test.test_date
%p
  %b Diagnostic test type:
  = @diagnostic_test.diagnostic_test_type
%p
  %b Result:
  = @diagnostic_test.result
%p
  %b Client:
  = @diagnostic_test.client_id

= link_to 'Edit', edit_diagnostic_test_path(@diagnostic_test)
\|
= link_to 'Back', diagnostic_tests_path