config/routes.rb
MedBase::Application.routes.draw do

  resources :desease_types

  resources :doctor_deseases

  resources :doctor_types

  resources :users

  resources :med_diagnostic_test_types

  resources :htm_help_types

  resources :hospitalization_types

  resources :diagnostic_test_types

  resources :ins_companies

  resources :client_sexes

  resources :clients do
    member do
      get :operations,:search
    end

   resources :lab_tests 
   resources :diagnostic_tests
   resources :hospitalizations
   resources :htm_help_notes
   resources :sanatorium_notes
   resources :med_diagnostic_tests
   resources :prof_inspections
  end

  resources :lab_test_types

  match 'csv' =>"clients#import_csv"

  root :to => 'welcome#index'  

end

app/models/prof_inspection.rb
class ProfInspection < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  validates :actual_date,:user_id,:conclusion,:client_id, :presence =>true
end

app/controllers/prof_inspections_controller.rb
class ProfInspectionsController < ApplicationController
  # GET /prof_inspections
  # GET /prof_inspections.json
  
  before_filter :find_client

  def find_client
    @client=Client.find(params[:client_id])
  end
  
  
  def index
    @prof_inspections = @client.prof_inspections


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prof_inspections }
    end
  end

  # GET /prof_inspections/1
  # GET /prof_inspections/1.json
  def show
    @prof_inspection = ProfInspection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prof_inspection }
    end
  end

  # GET /prof_inspections/new
  # GET /prof_inspections/new.json
  def new
    @prof_inspection = ProfInspection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prof_inspection }
    end
  end

  # GET /prof_inspections/1/edit
  def edit
    @prof_inspection = ProfInspection.find(params[:id])
  end

  # POST /prof_inspections
  # POST /prof_inspections.json
  def create
    @prof_inspection = ProfInspection.new(params[:prof_inspection])
    @prof_inspection.client=@client

    respond_to do |format|
      if @prof_inspection.save
        format.html { redirect_to client_prof_inspections_path(@client), notice: I18n.t(:record_created)}
        format.json { render json: @prof_inspection, status: :created, location: @prof_inspection }
      else
        format.html { render action: "new" }
        format.json { render json: @prof_inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prof_inspections/1
  # PUT /prof_inspections/1.json
  def update
    @prof_inspection = ProfInspection.find(params[:id])

    respond_to do |format|
      if @prof_inspection.update_attributes(params[:prof_inspection])
        format.html { redirect_to client_prof_inspections_path, notice: I18n.t(:record_updated)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @prof_inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prof_inspections/1
  # DELETE /prof_inspections/1.json
  def destroy
    @prof_inspection = ProfInspection.find(params[:id])
    @prof_inspection.destroy

    respond_to do |format|
      format.html { redirect_to client_prof_inspections_url }
      format.json { head :ok }
    end
  end
end

app/helpers/prof_inspections_helper.rb
module ProfInspectionsHelper
end

app/views/prof_inspections/_form.html.haml
=simple_form_for [@client,@prof_inspection] do |f|
  =f.error_notification
  =f.input :actual_date, :label => "Дата"
  = f.input :user,:label =>"Врач" do 
    = f.select :user_id, User.all.map { |u| [u.short_fio_with_doctor_type, u.id] }, :include_blank => false
  =f.input :conclusion, :label => "Заключение"
  = f.submit "Сохранить"

app/views/prof_inspections/_prof_inspection.html.haml
#san
  %b= l(item.actual_date)
  %p= "Врач: #{item.user.short_fio_with_doctor_type}"
  %p= "Заключение: #{item.conclusion}"

app/views/prof_inspections/edit.html.haml
%h1 Редактирование данных профосмотра

= render 'form'

= link_to 'Назад', client_prof_inspections_path

app/views/prof_inspections/index.html.haml
= link_to image_tag("",:class=>"ui-icon ui-icon-triangle-1-w"), operations_client_path(@client)
%br
%h1= @client.fio unless @client.nil?
%br
%h2 Данные о профосмотрах
%br

-unless flash.empty?
  %p#notice= notice

-if @prof_inspections.count > 0

  %table#newspaper-a
    %tr
      %th Дата
      %th Врач
      %th Заключение
      %th
      %th

    - @prof_inspections.each do |prof_inspection|
      %tr
        %td= l prof_inspection.actual_date
        %td= prof_inspection.user.short_fio_with_doctor_type
        %td= prof_inspection.conclusion
        %td= link_to image_tag("",:class => "ui-icon ui-icon-pencil"), edit_client_prof_inspection_path(@client,prof_inspection)
        %td= link_to image_tag("",:class => "ui-icon ui-icon-minus"), client_prof_inspection_path(@client,prof_inspection), :confirm => 'Are you sure?', :method => :delete
-else
  =render "clients/empty"
%br

= link_to 'Новая запись', new_client_prof_inspection_path

app/views/prof_inspections/new.html.haml
%h1 Новая запись

= render 'form'

= link_to 'Назад', client_prof_inspections_path(@client)

app/views/prof_inspections/show.html.haml
%p#notice= notice

%p
  %b Client:
  = @prof_inspection.client_id
%p
  %b Actual date:
  = @prof_inspection.actual_date
%p
  %b User:
  = @prof_inspection.user_id
%p
  %b Conclusion:
  = @prof_inspection.conclusion

= link_to 'Edit', edit_prof_inspection_path(@prof_inspection)
\|
= link_to 'Back', prof_inspections_path