config/routes.rb
MedBase::Application.routes.draw do

  resources :desease_types

  resources :doctor_deseases

  resources :doctor_types

  resources :users

  resources :med_diagnostic_test_types

  resources :htm_help_types

  resources :hospitalization_types

  resources :diagnostic_test_types

  resources :ins_companies

  resources :client_sexes

  resources :clients do
    member do
      get :operations,:search
    end

   resources :lab_tests 
   resources :diagnostic_tests
   resources :hospitalizations
   resources :htm_help_notes
   resources :sanatorium_notes
   resources :med_diagnostic_tests
   resources :prof_inspections
  end

  resources :lab_test_types

  match 'csv' =>"clients#import_csv"

  root :to => 'welcome#index'  

end

app/models/lab_test.rb
class LabTest < ActiveRecord::Base
  belongs_to :client
  belongs_to :lab_test_type

  validates :result,:test_date,:lab_test_type_id,:presence => true
end

app/models/lab_test_type.rb
class LabTestType < ActiveRecord::Base
  has_many :lab_tests
  validates :name,:presence => true


def can_be_deleted
  lab_tests.count<=0
end

  
end

app/controllers/lab_tests_controller.rb
class LabTestsController < ApplicationController
  # GET /lab_tests
  # GET /lab_tests.json
  before_filter :find_client
  
  def find_client
    @client=Client.find(params[:client_id])
  end

  
  def index
    @lab_tests = LabTest.where(:client_id => @client.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lab_tests }
    end
  end

  # GET /lab_tests/1
  # GET /lab_tests/1.json
  def show
    @lab_test = LabTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lab_test }
    end
  end

  # GET /lab_tests/new
  # GET /lab_tests/new.json
  def new
    @lab_test = LabTest.new
    @lab_test.test_date=Time.now

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lab_test }
    end
  end

  # GET /lab_tests/1/edit
  def edit
    @lab_test = LabTest.find(params[:id])
  end

  # POST /lab_tests
  # POST /lab_tests.json
  def create
    @lab_test = LabTest.new(params[:lab_test])
    @lab_test.client=@client


    respond_to do |format|
      if @lab_test.save
        format.html { redirect_to client_lab_tests_path(@client), notice: t(:lab_test_saved) }
        format.json { render json: @lab_test, status: :created, location: @lab_test }
      else
        format.html { render action: "new" }
        format.json { render json: @lab_test.errors, status: :unprocessable_entity }
      end
    end
 end

  # PUT /lab_tests/1
  # PUT /lab_tests/1.json
  def update
    @lab_test = LabTest.find(params[:id])

    respond_to do |format|
      if @lab_test.update_attributes(params[:lab_test])
        format.html { redirect_to client_lab_tests_path(@client), notice: t(:lab_test_saved) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lab_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_tests/1
  # DELETE /lab_tests/1.json
  def destroy
    @lab_test = LabTest.find(params[:id])
    @lab_test.destroy

    respond_to do |format|
      format.html { redirect_to client_lab_tests_path(@client), notice: t(:lab_test_deleted) }
      format.json { head :ok }
    end
  end
end

app/helpers/lab_tests_helper.rb
module LabTestsHelper
end

app/views/lab_tests/_form.html.haml
=simple_form_for [@client,@lab_test] do |f|
  =f.input :test_date,:label=>"Дата"
  =f.association :lab_test_type,:label=>"Тип анализа"
  =f.input :result, :label => "Результат"
  =f.submit "Сохранить"

app/views/lab_tests/_lab_test.html.haml
%p
  ="#{l item.test_date} | #{item.lab_test_type.name}: #{item.result}"

app/views/lab_tests/edit.html.haml
%h1 Editing lab_test

= render 'form'

= link_to 'Show', [@client,@lab_test]
\|
= link_to 'Back', client_lab_tests_path

app/views/lab_tests/index.html.haml
= link_to image_tag("",:class=>"ui-icon ui-icon-triangle-1-w"), operations_client_path(@client)
%br
%h1= @client.fio unless @client.nil?
%br
%h2 Лабораторные анализы
%br

-unless flash.empty?
  %p#notice= notice


-if @lab_tests.count > 0 
  %table#newspaper-a
    %tr
      %th Дата
      %th Тип
      %th Результат
      %th
      %th

    - @lab_tests.each do |lab_test|
      %tr
        %td= l lab_test.test_date
        %td= lab_test.lab_test_type.name
        %td= lab_test.result

        %td= link_to image_tag("",:class => "ui-icon ui-icon-pencil"),edit_client_lab_test_path(@client,lab_test)
        %td= link_to image_tag("",:class => "ui-icon ui-icon-minus"), client_lab_test_path(@client,lab_test), :confirm => 'Are you sure?', :method => :delete
-else
  =render "clients/empty"

%br

= link_to 'Новый анализ', new_client_lab_test_path 

app/views/lab_tests/new.html.haml
%h1 Новый лабораторный анализ

= render 'form'

= link_to 'Назад', client_lab_tests_path

app/views/lab_tests/show.html.haml
%p#notice= notice

%p
  %b Test date:
  = @lab_test.test_date
%p
  %b Lab test type:
  = @lab_test.lab_test_type_id
%p
  %b Client:
  = @lab_test.client_id
%p
  %b Result:
  = @lab_test.result

= link_to 'Edit', edit_client_lab_test_path(@lab_test)
\|
= link_to 'Back', client_lab_tests_path