config/routes.rb
MedBase::Application.routes.draw do

  resources :desease_types

  resources :doctor_deseases

  resources :doctor_types

  resources :users

  resources :med_diagnostic_test_types

  resources :htm_help_types

  resources :hospitalization_types

  resources :diagnostic_test_types

  resources :ins_companies

  resources :client_sexes

  resources :clients do
    member do
      get :operations,:search
    end

   resources :lab_tests 
   resources :diagnostic_tests
   resources :hospitalizations
   resources :htm_help_notes
   resources :sanatorium_notes
   resources :med_diagnostic_tests
   resources :prof_inspections
  end

  resources :lab_test_types

  match 'csv' =>"clients#import_csv"

  root :to => 'welcome#index'  

end

app/models/med_diagnostic_test.rb
class MedDiagnosticTest < ActiveRecord::Base
  belongs_to :med_diagnostic_test_type
  validates :test_date,:med_diagnostic_test_type_id,:result, :presence => true
  belongs_to :client
end

app/models/med_diagnostic_test_type.rb
class MedDiagnosticTestType < ActiveRecord::Base
  validates :name,:presence => true
  has_many :med_diagnostic_tests 



def can_be_deleted
  med_diagnostic_tests.count<=0
end

end

app/controllers/med_diagnostic_tests_controller.rb
class MedDiagnosticTestsController < ApplicationController
  # GET /med_diagnostic_tests
  # GET /med_diagnostic_tests.json
  before_filter :find_client

  def find_client
    @client=Client.find(params[:client_id])
  end

  def index
    @med_diagnostic_tests = @client.med_diagnostic_tests


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @med_diagnostic_tests }
    end
  end

  # GET /med_diagnostic_tests/1
  # GET /med_diagnostic_tests/1.json
  def show
    @med_diagnostic_test = MedDiagnosticTest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @med_diagnostic_test }
    end
  end

  # GET /med_diagnostic_tests/new
  # GET /med_diagnostic_tests/new.json
  def new
    @med_diagnostic_test = MedDiagnosticTest.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @med_diagnostic_test }
    end
  end

  # GET /med_diagnostic_tests/1/edit
  def edit
    @med_diagnostic_test = MedDiagnosticTest.find(params[:id])
  end

  # POST /med_diagnostic_tests
  # POST /med_diagnostic_tests.json
  def create
    @med_diagnostic_test = MedDiagnosticTest.new(params[:med_diagnostic_test])
    @med_diagnostic_test.client=@client

    respond_to do |format|
      if @med_diagnostic_test.save
        format.html { redirect_to client_med_diagnostic_tests_path(@client), notice: I18n.t(:record_saved) }
        format.json { render json: @med_diagnostic_test, status: :created, location: @med_diagnostic_test }
      else
        format.html { render action: "new" }
        format.json { render json: @med_diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /med_diagnostic_tests/1
  # PUT /med_diagnostic_tests/1.json
  def update
    @med_diagnostic_test = MedDiagnosticTest.find(params[:id])

    respond_to do |format|
      if @med_diagnostic_test.update_attributes(params[:med_diagnostic_test])
        format.html { redirect_to client_med_diagnostic_tests_path(@client), notice: I18n.t(:record_updated)}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @med_diagnostic_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /med_diagnostic_tests/1
  # DELETE /med_diagnostic_tests/1.json
  def destroy
    @med_diagnostic_test = MedDiagnosticTest.find(params[:id])
    @med_diagnostic_test.destroy

    respond_to do |format|
      format.html { redirect_to client_med_diagnostic_tests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/med_diagnostic_tests_helper.rb
module MedDiagnosticTestsHelper
end

app/views/med_diagnostic_tests/_form.html.haml
=simple_form_for [@client,@med_diagnostic_test] do |f|
  =f.error_notification
  =f.input :test_date,:label=>"Дата"
  =f.association :med_diagnostic_test_type,:label =>"Тип"
  =f.input :result,:label=>"Результат"
  =f.submit "Сохранить"

app/views/med_diagnostic_tests/_med_diagnostic_test.html.haml
%p
  ="#{l item.test_date} | #{item.med_diagnostic_test_type.name}: #{item.result}"

app/views/med_diagnostic_tests/edit.html.haml
%h1 Редактирование записи о лечебно-диагностической работе

= render 'form'

= link_to 'Назад', client_med_diagnostic_tests_path(@client)

app/views/med_diagnostic_tests/index.html.haml
= link_to image_tag("",:class=>"ui-icon ui-icon-triangle-1-w"), operations_client_path(@client)
%br
%h1= @client.fio unless @client.nil?
%br
%h2 Лечебно-диагностическая работа
%br

-unless flash.empty?
  %p#notice= notice

-if @med_diagnostic_tests.count >0 
  %table#newspaper-a
    %tr
      %th Дата
      %th Тип исследования
      %th Результат
      %th
      %th

    - @med_diagnostic_tests.each do |med_diagnostic_test|
      %tr
        %td= l med_diagnostic_test.test_date
        %td= med_diagnostic_test.med_diagnostic_test_type.name
        %td= med_diagnostic_test.result
        %td= link_to image_tag("",:class => "ui-icon ui-icon-pencil"),edit_client_med_diagnostic_test_path(@client,med_diagnostic_test)
        %td= link_to image_tag("",:class => "ui-icon ui-icon-minus"),client_med_diagnostic_test_path(@client,med_diagnostic_test), :confirm => 'Are you sure?', :method => :delete
-else
  =render "clients/empty"
%br

= link_to 'Новое исследование', new_client_med_diagnostic_test_path(@client)

app/views/med_diagnostic_tests/new.html.haml
%h1 Новая запись о лечебно-диагностической работе

= render 'form'

= link_to 'Назад', client_med_diagnostic_tests_path(@client)

app/views/med_diagnostic_tests/show.html.haml
%p#notice= notice

%p
  %b Test date:
  = @diagnostic_test.test_date
%p
  %b Diagnostic test type:
  = @diagnostic_test.diagnostic_test_type
%p
  %b Result:
  = @diagnostic_test.result
%p
  %b Client:
  = @diagnostic_test.client_id

= link_to 'Edit', edit_diagnostic_test_path(@diagnostic_test)
\|
= link_to 'Back', diagnostic_tests_path